[discord]
client_id = ""
client_token = ""

[discord.ids]
log_channel_id = ""
mr_role_id = ""
dev_ids = ["1344176447551574078", "1138235120424325160"] # Async, Sheep

[database]
client = "mysql2"
host = ""
port = "3306"
user = ""
password = ""
schema = ""

[sentry]
dsn = ""

[roles]
mr_role = ""